// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKOX7dlutfCymiz_KYmWB7jJPje--c480',
    appId: '1:1006642355965:web:5d4f673ed48d18d7256894',
    messagingSenderId: '1006642355965',
    projectId: 'authenticationpractice-6abe2',
    authDomain: 'authenticationpractice-6abe2.firebaseapp.com',
    storageBucket: 'authenticationpractice-6abe2.appspot.com',
    measurementId: 'G-96BKG4VW9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5eTwRIGoZnEf3KU7bCyMU1r1eWjdGrnw',
    appId: '1:1006642355965:android:5ba3eeb0399100d1256894',
    messagingSenderId: '1006642355965',
    projectId: 'authenticationpractice-6abe2',
    storageBucket: 'authenticationpractice-6abe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8c0wAnSyG1zH9I5mYVi7qVooOQsPR28k',
    appId: '1:1006642355965:ios:61ccb106c522669a256894',
    messagingSenderId: '1006642355965',
    projectId: 'authenticationpractice-6abe2',
    storageBucket: 'authenticationpractice-6abe2.appspot.com',
    iosBundleId: 'com.example.authpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8c0wAnSyG1zH9I5mYVi7qVooOQsPR28k',
    appId: '1:1006642355965:ios:61ccb106c522669a256894',
    messagingSenderId: '1006642355965',
    projectId: 'authenticationpractice-6abe2',
    storageBucket: 'authenticationpractice-6abe2.appspot.com',
    iosBundleId: 'com.example.authpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKOX7dlutfCymiz_KYmWB7jJPje--c480',
    appId: '1:1006642355965:web:5d4f673ed48d18d7256894',
    messagingSenderId: '1006642355965',
    projectId: 'authenticationpractice-6abe2',
    authDomain: 'authenticationpractice-6abe2.firebaseapp.com',
    storageBucket: 'authenticationpractice-6abe2.appspot.com',
    measurementId: 'G-96BKG4VW9J',
  );
}
